#!/usr/bin/env python


people={

	'yangji':{

	    'phone':'null',
	    'addr':'guangyuan'
	},

	'yt':{
	    'phone':'63193',
            'addr':'shanghai'
	},
	'zhangxu':{
	    'phone':'69082',
	    'addr':'luzhou'
	},
	'zhoujun':{
	    'phone':'null',
	    'addr':'chongqing'
	},
	'shezhang':{
	    'phone':'67233',
	    'addr':'suining'
	},
	'zhouxiaoyong':{
	    'phone':'62790',
	    'addr':'jinxi'
	}
}


labels={
	'phone':'phone number',
        'addr':'address'
}
name=raw_input('name:')



request=raw_input('phone number (p)or addres (a)?')


if request =='p':key='phone'
if request =='a':key='addr'
if name in people :print "%s's %s is %s." % \
	(name, labels[key], people[name][key]) 
